// GENERATED by make_rapidapi_spec.py — do not edit by hand; edit the config
// at the top of make_rapidapi_spec.py and re-run it.
//
// RapidAPI endpoint + params reorder — paste into the browser console on a
// logged-in rapidapi.com tab (DevTools -> Console -> paste -> Enter).
//
// What it does, in order:
//   1. Fetches the version's endpoints with their params.
//   2. For EACH endpoint whose params are out of spec order, replays the
//      dashboard's updateEndpointWithParameters mutation with the params
//      re-indexed to match the spec (ids, descriptions, payloads preserved).
//   3. Reorders the endpoints themselves (updateEndpointsCollectionOrder).
//   4. Re-fetches and prints the final state.
//
// If calls fail with 401/403, refresh CSRF_TOKEN in make_rapidapi_spec.py
// (DevTools -> Network -> any "graphql" request -> request headers ->
// csrf-token) and regenerate, or just edit the constant below.

(async () => {
  const API_ID = 'api_REPLACE_ME';
  const CSRF_TOKEN = 'REPLACE_ME';
  const API_VERSION_ID = ''; // optional; empty = use the current version
  const DRY_RUN = false; // true = only print what would change
  const SPEC = {
  "paths": {
    "/properties/search-sale": {
      "get": {
        "parameters": [
          {
            "name": "location"
          },
          {
            "name": "price_min"
          },
          {
            "name": "price_max"
          },
          {
            "name": "beds_min"
          },
          {
            "name": "beds_max"
          },
          {
            "name": "property_type"
          },
          {
            "name": "added"
          },
          {
            "name": "keywords"
          },
          {
            "name": "radius"
          },
          {
            "name": "sort"
          },
          {
            "name": "page"
          }
        ]
      }
    },
    "/locations/auto-complete": {
      "get": {
        "parameters": [
          {
            "name": "query"
          }
        ]
      }
    },
    "/properties/search-rent": {
      "get": {
        "parameters": [
          {
            "name": "location"
          },
          {
            "name": "price_min"
          },
          {
            "name": "price_max"
          },
          {
            "name": "beds_min"
          },
          {
            "name": "beds_max"
          },
          {
            "name": "property_type"
          },
          {
            "name": "furnished_state"
          },
          {
            "name": "added"
          },
          {
            "name": "keywords"
          },
          {
            "name": "radius"
          },
          {
            "name": "sort"
          },
          {
            "name": "page"
          }
        ]
      }
    },
    "/properties/search-new-homes": {
      "get": {
        "parameters": [
          {
            "name": "location"
          },
          {
            "name": "price_min"
          },
          {
            "name": "price_max"
          },
          {
            "name": "beds_min"
          },
          {
            "name": "beds_max"
          },
          {
            "name": "property_type"
          },
          {
            "name": "added"
          },
          {
            "name": "keywords"
          },
          {
            "name": "radius"
          },
          {
            "name": "sort"
          },
          {
            "name": "page"
          }
        ]
      }
    },
    "/properties/details": {
      "get": {
        "parameters": [
          {
            "name": "listing_id"
          }
        ]
      }
    },
    "/properties/agent-contact": {
      "get": {
        "parameters": [
          {
            "name": "listing_id"
          }
        ]
      }
    },
    "/house-prices/search": {
      "get": {
        "parameters": [
          {
            "name": "location"
          },
          {
            "name": "page"
          }
        ]
      }
    },
    "/house-prices/estimate": {
      "get": {
        "parameters": [
          {
            "name": "address"
          }
        ]
      }
    },
    "/agents/search": {
      "get": {
        "parameters": [
          {
            "name": "location"
          },
          {
            "name": "page"
          },
          {
            "name": "search_type"
          }
        ]
      }
    },
    "/agents/details": {
      "get": {
        "parameters": [
          {
            "name": "branch_id"
          }
        ]
      }
    },
    "/agents/listings": {
      "get": {
        "parameters": [
          {
            "name": "branch_id"
          },
          {
            "name": "section"
          }
        ]
      }
    }
  }
};

  if (!/^api_/.test(API_ID)) throw new Error('API_ID is still the stub. Paste your real api_... id.');
  if (!CSRF_TOKEN || CSRF_TOKEN.length < 10) throw new Error('CSRF_TOKEN is still the stub.');
  if (typeof SPEC !== 'object' || !SPEC.paths || !Object.keys(SPEC.paths).length) {
    throw new Error('SPEC is still the stub. It must be an object with a non-empty "paths" key.');
  }

  const desiredOrder = Object.keys(SPEC.paths);

  const stripTypename = (v) => {
    if (Array.isArray(v)) return v.map(stripTypename);
    if (v && typeof v === 'object') {
      const out = {};
      for (const [k, val] of Object.entries(v)) if (k !== '__typename') out[k] = stripTypename(val);
      return out;
    }
    return v;
  };

  const gql = async (operationName, query, variables) => {
    const res = await fetch('https://rapidapi.com/gateway/graphql', {
      method: 'POST',
      credentials: 'include',
      headers: {
        accept: '*/*',
        'content-type': 'application/json',
        'csrf-token': CSRF_TOKEN,
        'rapid-client': 'provider-dashboard-service',
      },
      body: JSON.stringify({ operationName, variables, extensions: {}, query }),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}: ${(await res.text()).slice(0, 300)}`);
    const json = await res.json();
    if (json.errors && json.errors.length) throw new Error('GraphQL errors: ' + JSON.stringify(json.errors, null, 2));
    return json.data;
  };

  const resolveVersionId = async () => {
    if (API_VERSION_ID) return API_VERSION_ID;
    const data = await gql(
      'getVersions',
      `query getVersions($apiId: ID!) { api(id: $apiId) { id name versions { id name current versionStatus } } }`,
      { apiId: API_ID }
    );
    const v = data.api.versions.find((x) => x.current);
    if (!v) throw new Error('Could not resolve a current version — set API_VERSION_ID.');
    console.log(`API: ${data.api.name} — using current version ${v.name} (${v.id})`);
    return v.id;
  };

  const fetchEndpoints = async (apiVersionId) => {
    const data = await gql(
      'GetDataForEndpoints',
      `query GetDataForEndpoints($apiVersionId: ID!) {
        apiVersion(apiVersionId: $apiVersionId) {
          id
          endpoints(pagingArgs: {limit: -1}) {
            id index method name route description group
            response displayResponse isMockResponse mockResponseId
            params { optional required headers constant }
            responsePayloads { id name format body headers description status statusCode examples schema }
            requestPayloads { id name format body description examples schema }
            externalDocs { description url }
          }
        }
      }`,
      { apiVersionId }
    );
    return stripTypename(data.apiVersion.endpoints).sort((a, b) => a.index - b.index);
  };

  // Build the params.route entry shape the dashboard sends in
  // updateEndpointWithParameters (drop createdAt/updatedAt/endpoint/type).
  const toRouteParam = (p, index) => {
    const out = {
      index,
      id: p.id,
      name: p.name,
      querystring: p.querystring,
      paramType: p.paramType,
      condition: p.condition,
      description: p.description,
      status: p.status,
      schema: p.schema,
      schemaDefinition: p.schemaDefinition,
    };
    if (p.value !== undefined) out.value = p.value;
    return out;
  };

  const specParamNames = (route) => {
    const item = SPEC.paths[route] || {};
    const op = item.get || item.post || Object.values(item)[0] || {};
    return (op.parameters || []).map((p) => p.name);
  };

  // Reorder one endpoint's route params to spec order; returns null if already ordered.
  const buildParamsUpdate = (e) => {
    const live = [...(e.params?.required || []), ...(e.params?.optional || [])];
    if ((e.params?.constant || []).length) {
      console.warn(`  ${e.route}: has CONSTANT params — leaving them untouched (not supported by this script).`);
    }
    if (!live.length) return null;

    const wanted = specParamNames(e.route);
    const byName = new Map(live.map((p) => [p.name, p]));
    const ordered = wanted.filter((n) => byName.has(n)).map((n) => byName.get(n));
    const leftovers = live.filter((p) => !wanted.includes(p.name));
    if (leftovers.length) {
      console.warn(`  ${e.route}: params not in spec, appending at end: ${leftovers.map((p) => p.name).join(', ')}`);
    }
    const finalList = [...ordered, ...leftovers];
    const changed = finalList.some((p, i) => p.index !== i);
    if (!changed) return null;

    return {
      name: e.name,
      description: e.description,
      externalDocs: e.externalDocs || {},
      apiVersionId: undefined, // filled by caller
      params: {
        route: finalList.map(toRouteParam),
        header: (e.params?.headers || []).map(toRouteParam),
      },
      payloadParameters: [],
      method: e.method,
      displayResponse: e.displayResponse ?? false,
      response: e.response ?? '',
      responsePayloads: (e.responsePayloads || []).map((p) => ({
        id: p.id,
        name: p.name,
        format: p.format,
        body: p.body ?? '',
        headers: p.headers ?? '{}',
        description: p.description,
        status: p.status,
        statusCode: p.statusCode,
        examples: p.examples,
        schema: p.schema,
      })),
      requestPayloads: e.requestPayloads || [],
      mockResponseId: e.mockResponseId ?? null,
      route: e.route,
      routeregex: e.route,
      endpointId: e.id,
    };
  };

  const updateEndpointParams = (input) =>
    gql(
      'updateEndpointWithParameters',
      `mutation updateEndpointWithParameters($input: updateOrCreateEndpointWithParameters!) {
        updateOrCreateEndpointWithParameters(input: $input)
      }`,
      { input }
    );

  const reorderEndpoints = (plan) =>
    gql(
      'updateEndpointsCollectionOrder',
      `mutation updateEndpointsCollectionOrder($endpointsCollectionOrder: [EndpointOrder]) {
        updateEndpointsCollectionOrder(endpointsCollectionOrder: $endpointsCollectionOrder)
      }`,
      { endpointsCollectionOrder: plan }
    );

  const printState = (endpoints) => {
    console.table(
      endpoints.map((e) => ({
        index: e.index,
        route: e.route,
        params: [...(e.params?.required || []), ...(e.params?.optional || [])]
          .sort((a, b) => a.index - b.index)
          .map((p) => p.name)
          .join(', '),
      }))
    );
  };

  // ------------------------------ run --------------------------------------
  const apiVersionId = await resolveVersionId();
  const endpoints = await fetchEndpoints(apiVersionId);
  console.log('Current state:');
  printState(endpoints);

  const byRoute = new Map(endpoints.map((e) => [e.route, e]));
  const missing = desiredOrder.filter((r) => !byRoute.has(r));
  if (missing.length) throw new Error(`Spec routes not found in this version: ${missing.join(', ')}`);
  const extra = endpoints.filter((e) => !desiredOrder.includes(e.route));
  if (extra.length) throw new Error(`Endpoints not in spec: ${extra.map((e) => e.route).join(', ')}`);

  // Step 1: per-endpoint param reorder.
  console.log('\nStep 1 — params:');
  let paramUpdates = 0;
  for (const route of desiredOrder) {
    const e = byRoute.get(route);
    const input = buildParamsUpdate(e);
    if (!input) {
      console.log(`  ${route}: params already in spec order`);
      continue;
    }
    input.apiVersionId = apiVersionId;
    const order = input.params.route.map((p) => p.name).join(', ');
    if (DRY_RUN) {
      console.log(`  ${route}: WOULD reorder params -> ${order}`);
    } else {
      await updateEndpointParams(input);
      console.log(`  ${route}: params reordered -> ${order}`);
    }
    paramUpdates++;
  }
  if (!paramUpdates) console.log('  nothing to do');

  // Step 2: endpoint order.
  const endpointPlan = desiredOrder.map((route, index) => ({ endpointId: byRoute.get(route).id, index }));
  const endpointChanges = desiredOrder.filter((route, i) => byRoute.get(route).index !== i);
  console.log(`\nStep 2 — endpoint order: ${endpointChanges.length} of ${endpointPlan.length} need moving`);
  if (endpointChanges.length && !DRY_RUN) {
    await reorderEndpoints(endpointPlan);
    console.log('  applied');
  }

  // Step 3: verify.
  if (!DRY_RUN) {
    console.log('\nFinal state:');
    printState(await fetchEndpoints(apiVersionId));
  } else {
    console.log('\nDRY_RUN was on — nothing was changed.');
  }
})();
